In [1]:
# 把学生的平均分计算出来

In [7]:
import jutil
import pandas as pd
import numpy as np

In [22]:
def load_college_students_df(college_code):
    sql = "select *,CONVERT(VARCHAR,birthday,112) as birth from view_stu_course_mark where college_code='%s' and grade='2014'" % college_code
    return jutil.load_pd_df(sql)

In [23]:
# 信息学院
df = load_college_students_df('04')
df.head()

,birth,birthday,city,class_code,class_name,college_code,college_name,course_code,course_name,course_type,...,province,sex,speciality_code,speciality_name,student_id,teach_class_id,teacher,term_id,term_name,term_order
0,19960615,834768000000,北京,0403201403,通信2014-03班,04,信息科学与技术学院,0471006,计算机组成原理C,必,...,北京,男,0403,通信工程,20122169,3,唐慧佳,79,2016-2017第1学期,3
1,19960615,834768000000,北京,0403201403,通信2014-03班,04,信息科学与技术学院,0471007,现代交换原理,限,...,北京,男,0403,通信工程,20122169,2,刘恒,72,2014-2015第2学期,2
2,19960615,834768000000,北京,0403201403,通信2014-03班,04,信息科学与技术学院,0473001,DSP原理与应用,限,...,北京,男,0403,通信工程,20122169,1,邹应全,75,2015-2016第1学期,2
3,19960615,834768000000,北京,0403201403,通信2014-03班,04,信息科学与技术学院,1271002,随机过程C,必,...,北京,男,0403,通信工程,20122169,1,彭皓,73,2014-2015第1学期补考,1
4,19960615,834768000000,北京,0403201403,通信2014-03班,04,信息科学与技术学院,3006654,电路分析BⅠ,必,...,北京,男,0403,通信工程,20122169,4,谭永霞,64,2012-2013第2学期,0

In [27]:
# 要根据学生id聚类然后计算其平均分
def get_avg_stu_marks_df(df):
    groupd  = df.groupby(['student_id','college_code','college_name','sex','name','birth','class_code','class_name','nation_name',
        'party','province','city','speciality_code','speciality_name','grade'],as_index=False) # 保留列
    groupd = groupd.agg({'pmark':np.average})
    return groupd

In [28]:
marks = get_avg_stu_marks_df(df)
marks.head()

,student_id,college_code,college_name,sex,name,birth,class_code,class_name,nation_name,party,province,city,speciality_code,speciality_name,grade,pmark
0,20122169,04,信息科学与技术学院,男,王钧毅,19960615,0403201403,通信2014-03班,汉族,中国共产主义青年团团员,北京,北京,0403,通信工程,2014,53.827358
1,20122639,04,信息科学与技术学院,男,杨永虎,19920702,0408201402,软件2014-02班,汉族,中国共产党预备党员,山东,聊城市,0408,软件工程,2014,84.775641
2,20130068,04,信息科学与技术学院,男,任添笑,19950615,0402201401,计算机2014-01班,汉族,中国共产主义青年团团员,陕西,西安市,0402,计算机科学与技术,2014,81.977778
3,20131649,04,信息科学与技术学院,男,王鑫,19940202,0406201401,自动2014-01班,汉族,中国共产主义青年团团员,重庆,重庆市,0406,自动化,2014,61.821591
4,20131664,04,信息科学与技术学院,男,盛守彬,19940208,0406201402,自动2014-02班,汉族,中国共产主义青年团团员,辽宁,本溪市,0406,自动化,2014,55.774000

In [38]:
sex_cnt = marks['sex'].value_counts()
dict(sex_cnt)

{'女': 176, '男': 517}